version: '3.9'
services:
  mongodb:
    image: mongo:5.0
    command: mongod --port 27018
    ports:
      - 27018:27018
    volumes:
      - ~/apps/mongo:/data/mongodb
    container_name: mongodb
    networks:
      - network-api
  api:
    build:
      context: './deploy'
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - network-api
networks:
  network-api:
    driver: bridge